import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "providers";
import { Auth } from "@/components/auth/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <Providers>
                    <Auth>
                        <div className="flex h-screen bg-gray-100">
                            {/* Sidebar */}
                            <div className="w-64 space-y-6 py-7 px-2 absolute inset-y-0 left-0 transform -translate-x-full md:relative md:translate-x-0 transition duration-200 ease-in-out">
                                {/* Sidebar content here */}
                                <nav>
                                    <a
                                        href="#"
                                        className="block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700"
                                    >
                                        Link 1
                                    </a>
                                    <a
                                        href="#"
                                        className="block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700"
                                    >
                                        Link 2
                                    </a>
                                    <a
                                        href="#"
                                        className="block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-700"
                                    >
                                        Link 3
                                    </a>
                                </nav>
                            </div>

                            {/* Main content */}
                            <div className="flex-1 flex flex-col overflow-hidden">
                                {/* Header */}
                                <header className="flex justify-between items-center p-4 shadow-md">
                                    {/* Header content here */}
                                    <span>Header</span>
                                </header>

                                {/* Main body content */}
                                <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
                                    <div className="container mx-auto px-4 py-8">
                                        {children}
                                    </div>
                                </main>
                            </div>
                        </div>
                    </Auth>
                </Providers>
            </body>
        </html>
    );
}
